bind 127.0.0.1
protected-mode yes
port 26379
daemonize yes
supervised no
pidfile "sentinel.pid"
logfile "sentinel.log"
dir "data"
requirepass "zhuyanjun+123"
sentinel monitor mymaster 127.0.0.1 6380 1
sentinel auth-pass mymaster "zhuyanjun+123"
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 10000
