bind 127.0.0.1
protected-mode yes
port 6380
daemonize yes
supervised no
pidfile "redis.pid"
logfile "redis.log"
dir "data"
dbfilename "dump.rdb"
appendonly yes
appendfilename "appendonly.aof"
requirepass "zhuyanjun+123"
masterauth "zhuyanjun+123"
